wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.18
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.1
    start_time: 1693692743
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 16
      4: 3.9.1
      5: 0.12.18
      8:
      - 3
      - 5
batchsize_discriminator:
  desc: null
  value: 512
batchsize_ppo:
  desc: null
  value: 12
entropy_reg:
  desc: null
  value: 0
env_id:
  desc: null
  value: randomized_v2
env_steps:
  desc: null
  value: 3000000.0
epsilon:
  desc: null
  value: 0.1
gamma:
  desc: null
  value: 0.999
lambd:
  desc: null
  value:
  - 1
  - 10
n_workers:
  desc: null
  value: 12
ppo_epochs:
  desc: null
  value: 5
